#!/usr/bin/env python3
"""build_index.py - generated indexes for the FINDINGS archive and claims dir.

2026-08-26, DOC GOVERNANCE mechanism 5 support. Additive only: writes two
generated files, never moves or edits a source document (cross-references cite
filenames and entry numbers by string; mass reorganization would break them).

Outputs:
  RE_output/INDEX_findings.md   one line per ## N.N entry + supersession links
                                + per-series rollups
  RE_output/INDEX_claims.md     claims/*.md|*.py with size/mtime/external
                                refcount/probe-family, orphan-flagged

Usage:
  python3 RE_scripts/build_index.py            # rebuild both indexes
  python3 RE_scripts/build_index.py --lint     # problems only, exit 1 if any

Lint items: entries whose timestamp could not be located (the 2026-08-16
convention requires one), claims cited by nothing (orphan candidates - review,
do not delete blindly).

Exit codes: 0 clean, 1 lint violations, 2 environment error.
ASCII-only per project rule (no em-dashes in code/comments).
"""
import re
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FINDINGS_GLOB = "FINDINGS_2026-*.md"
FINDINGS_DIRS = ["", "findings"]  # root or findings/ (phase-B layout)
CLAIMS_DIR = ROOT / "RE_output" / "claims"
OUT_FINDINGS = ROOT / "RE_output" / "INDEX_findings.md"
OUT_CLAIMS = ROOT / "RE_output" / "INDEX_claims.md"
RUN_ROOT = ROOT  # rebound by --root in main(); used for relative display paths

ENTRY_RE = re.compile(r"^## (\d+\.\d+[a-z]?)[ \t]+(.*)$")
# continuation heading lines that belong to the previous entry's header block
TS_RE = re.compile(r"\((20\d{2}-\d{2}-\d{2}[^\n)]*\))")
VALID_TS = re.compile(r"^20\d{2}-08")
LINK_PATTERNS = [
    re.compile(r"supersed\w*\s+(?:entry\s+)?(\d+\.\d+[a-z]?)", re.I),
    re.compile(r"(?:corrects|corrected\s+by|correction\s+(?:to|of))\s+(\d+\.\d+[a-z]?)", re.I),
    re.compile(r"retract\w*\s*(?:->|entry)?\s*(\d+\.\d+[a-z]?)", re.I),
    re.compile(r"renumbered\s+(?:\w+\s+)*?from\s+(\d+\.\d+[a-z]?)", re.I),
    re.compile(r"refut\w*\s+(?:entry\s+)?(\d+\.\d+[a-z]?)", re.I),
]


def parse_findings(findings_dir):
    """Return list of dicts: id, file, title, ts, text, links."""
    entries = []
    files = []
    for d in FINDINGS_DIRS:
        files += list((findings_dir / d).glob(FINDINGS_GLOB)) if d else \
            list(findings_dir.glob(FINDINGS_GLOB))
    files = sorted(set(files), reverse=True)
    cur = None
    for path in files:
        try:
            lines = path.read_text(encoding="utf8", errors="replace").splitlines()
        except OSError as exc:
            print(f"WARN unreadable {path.name}: {exc}", file=sys.stderr)
            continue
        cur = None
        for line in lines:
            m = ENTRY_RE.match(line)
            if m:
                cur = {
                    "id": m.group(1), "file": path.name,
                    "title": [m.group(2)], "text": [], "ts": None,
                }
                entries.append(cur)
            elif cur is None:
                continue  # preamble before first entry
            elif line.startswith("## "):
                cur["title"].append(line[3:].strip())  # multi-line heading
            else:
                cur["text"].append(line)
        # end of file leaves cur open; entries already registered
    for e in entries:
        e["title"] = " ".join(t for t in e["title"] if t).strip()
        # timestamp hunt: title block first, then first 12 body lines;
        # multiple candidates -> earliest VALID one wins (Bungie-era dates in
        # quoted material must not poison the sort).
        cands = TS_RE.findall(e["title"]) + \
            TS_RE.findall("\n".join(e["text"][:12]))
        cands = [c.strip().strip("(),") for c in cands if VALID_TS.match(c)]
        e["ts"] = min(cands) if cands else ""
        e["text"] = "\n".join(e["text"])
        links = []
        for pat in LINK_PATTERNS:
            links.extend(pat.findall(e["title"] + " " + e["text"]))
        e["links"] = sorted(set(links) - {e["id"]})
    return entries


def family_of(entry_id):
    return entry_id.split(".")[0]


def write_findings_index(entries):
    out = ["# INDEX findings (GENERATED by RE_scripts/build_index.py - never hand-edit)",
           f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')} | "
           f"{len(entries)} entries across {FINDINGS_GLOB}",
           "", "Links column = supersession/correction/retraction/renumber refs",
           "found in the entry text. Walk links upward before trusting an entry.",
           ""]
    out.append("## SERIES ROLLUPS")
    fams = {}
    for e in reversed(entries):  # oldest first for first-seen ordering
        fams.setdefault(family_of(e["id"]), []).append(e)
    for fam, es in fams.items():
        times = [e["ts"][:16] for e in es if e["ts"]]
        out.append(f"- {fam}.x | {len(es)} entries | "
                   f"last seen {max(times) if times else '?'} | "
                   f"{es[-1]['file']}")
    out.append("")
    last_fam = None
    for e in entries:  # newest-first overall
        if family_of(e["id"]) != last_fam:
            last_fam = family_of(e["id"])
            out.append(f"## SERIES {last_fam}.x")
        links = (", ".join("supersedes " + l for l in e["links"][:4])
                 or "-")
        title = e["title"][:110] + ("..." if len(e["title"]) > 110 else "")
        out.append(f"| {e['id']} | {e['ts'][:16]} | {e['file'].replace('FINDINGS_', '').replace('.md', '')} "
                   f"| {links} | {title} |")
    OUT_FINDINGS.write_text("\n".join(out), encoding="utf8")


def write_claims_index():
    files = sorted(list(CLAIMS_DIR.glob("*.md")) + list(CLAIMS_DIR.glob("*.py")))
    corpus_files = (
        list(ROOT.glob("*.md"))
        + list(CLAIMS_DIR.glob("*.md"))
    )
    corpus = {}
    for cf in corpus_files:
        try:
            corpus[cf.name] = cf.read_text(encoding="utf8", errors="replace")
        except OSError:
            corpus[cf.name] = ""
    rows = []
    fam_counts = {}
    for p in files:
        stem = p.stem.lower()
        rel = str(p.relative_to(RUN_ROOT))
        st = p.stat()
        refs = 0
        ref_files = []
        for name, text in corpus.items():
            if name == p.name:
                continue
            c = text.lower().count(stem)
            if c and len(stem) >= 6:  # ignore degenerate short stems
                refs += c
                ref_files.append(name)
        probe_m = re.match(r"^(.*?)(?:_?probe\d*[a-z]?|_?hunt\d*|_?sweep\d*)$", p.stem, re.I)
        fam = probe_m.group(1) if probe_m else ""
        if fam:
            fam_counts[fam] = fam_counts.get(fam, 0) + 1
        rows.append((p.name, st.st_size, datetime.fromtimestamp(st.st_mtime).strftime("%m-%d"),
                     refs, ", ".join(ref_files[:3]), fam))
    out = ["# INDEX claims (GENERATED by RE_script s/build_index.py - never hand-edit)",
           f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')} | "
           f"{sum(1 for r in rows if r[0].endswith('.md'))} deliverables, "
           f"{sum(1 for r in rows if r[0].endswith('.py'))} scripts",
           "",
           "refs = external mention count (root docs + other claims). Zero =",
           "ORPHAN CANDIDATE: review before archiving, some were inputs to a conclusion.",
           ""]
    out.append("| file | KB | mtime | refs | cited-in | family | flag |")
    out.append("|---|---|---|---|---|---|---|")
    for name, size, mt, refs, where, fam in rows:
        kb = max(1, size // 1024)
        flag = "**ORPHAN**" if refs == 0 else ""
        out.append(f"| {name} | {kb} | {mt} | {refs} | {where} | {fam} | {flag} |")
    out.append("")
    out.append("## PROBE FAMILIES (long numeric tails = lesson U7 escalation fired late)")
    for fam, n in sorted(fam_counts.items(), key=lambda kv: -kv[1]):
        verdict = CLAIMS_DIR / (fam.rstrip("_") + ".md")
        note = "closed->" + verdict.name if verdict.exists() else "NO VERDICT DOC"
        out.append(f"- {fam}: {n} members | {note}")
    OUT_CLAIMS.write_text("\n".join(out), encoding="utf8")
    return rows


def main(argv):
    root = ROOT
    if "--root" in argv:  # index a different checkout's corpus (e.g. main)
        root = Path(argv[argv.index("--root") + 1]).resolve()
    # rebind module paths so write_* and glob helpers follow --root
    global CLAIMS_DIR, OUT_FINDINGS, OUT_CLAIMS, RUN_ROOT
    CLAIMS_DIR = root / "RE_output" / "claims"
    OUT_FINDINGS = root / "RE_output" / "INDEX_findings.md"
    OUT_CLAIMS = root / "RE_output" / "INDEX_claims.md"
    RUN_ROOT = root
    findings_dir = root
    lint_only = "--lint" in sys.argv
    entries = parse_findings(findings_dir)
    problems = []
    undated = [e for e in entries if not e["ts"]]
    if undated:
        problems.append(f"{len(undated)} entries without a locatable timestamp:")
        problems += [f"  {e['file']} :: {e['id']} :: {e['title'][:60]}" for e in undated]
    if lint_only:
        stale = OUT_FINDINGS.exists() and any(
            OUT_FINDINGS.stat().st_mtime < p.stat().st_mtime
            for p in findings_dir.glob(FINDINGS_GLOB))
        if stale:
            problems.append("INDEX_findings.md older than newest FINDINGS file (stale index)")
        if problems:
            print("LINT FAIL")
            print("\n".join(problems))
            return 1
        print("LINT PASS (all entries carry timestamps; index fresh)")
        return 0
    if not entries:
        print("ERROR: no findings entries parsed - glob miss or parser bug", file=sys.stderr)
        return 2
    write_findings_index(entries)
    rows = write_claims_index() if CLAIMS_DIR.exists() else []
    n_orph = sum(1 for r in rows if r[5:] and r[3] == 0)
    print(f"wrote {OUT_FINDINGS.relative_to(RUN_ROOT)} ({len(entries)} entries, "
          f"{len([e for e in entries if e['ts']])} dated)")
    print(f"wrote {OUT_CLAIMS.relative_to(RUN_ROOT)} ({len(rows)} files, {n_orph} orphan candidates)")
    if undated:
        print(f"NOTE: {len(undated)} entries lack timestamps - run --lint for the list")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
