#!/usr/bin/env bash
# organize_root.sh - PHASE B of the 2026-08-31 root reorganization.
# Moves FINDINGS_*.md into findings/ and finalizes the layout.
#
# SAFETY INTERLOCK: refuses to run unless (a) the working tree has no
# modifications to the files it moves, and (b) no file in the repo root was
# modified in the last 30 minutes (the pen session must be idle - moving its
# active write target mid-session is the damage we are avoiding).
# The tooling (reconcile/build_index/bootstrap_check) already accepts BOTH
# locations, so after this script nothing else needs to change.
set -eu
cd "$(dirname "$0")/.." || exit 2

now=$(date +%s)
recent=0
for f in *.md; do
  [ -f "$f" ] || continue
  m=$(stat -f %m "$f" 2>/dev/null || stat -c %Y "$f")
  if [ $((now - m)) -lt 1800 ]; then recent=1; echo "recent: $f"; fi
done
if [ "$recent" -eq 1 ]; then
  echo "REFUSING: a root document was modified within 30 minutes -"
  echo "the pen session may be active. Run at a clean handoff."
  exit 1
fi
if [ -n "$(git status --porcelain FINDINGS_2026-*.md 2>/dev/null)" ]; then
  echo "REFUSING: FINDINGS files have uncommitted changes - commit first."
  exit 1
fi

mkdir -p findings
git mv FINDINGS_2026-*.md findings/ 2>/dev/null || mv FINDINGS_2026-*.md findings/
echo "moved $(ls findings | wc -l | tr -d ' ') findings file(s) into findings/"

# finalize the router path (FINDINGS row) - the router is regenerated by
# sessions, so only the path prefix needs fixing here
sed -i '' 's#| FINDINGS_2026-\*.md | append-only archive |#| findings/ (FINDINGS_2026-*.md) | append-only archive |#' AGENTS.md 2>/dev/null || true

/usr/bin/python3 RE_scripts/reconcile.py | tail -1
python3 RE_scripts/build_index.py | tail -2
bash RE_scripts/bootstrap_check.sh | tail -1
echo "PHASE B COMPLETE - root holds only live documents."
